In [1]:
###总结concatenate、stack、hstack、vstack、dstack都是将多个序列连接起来的方法，只是连接的方法不同；

# concatenate（cat）是在 存在的维度上 连接序列，并且除了操作的维度，其他维度的尺寸要相同；

# stack是在增加的 新的维度 上连接序列，需要连接的所有序列的所有维度都要相同；


# vstack、hstack相当于stack在axis=0，axis=1的轴上的操作;
# stack、vstack、hstack相当于增加新的维度之后的concatenate。

###实例
#在深度学习处理图像时，常用的有3通道的RGB彩色图像及单通道的灰度图。
#张量size为cxhxw,即通道数x图像高度x图像宽度。在用torch.cat拼接两张图像时一般要求图像大小一致而通道数可不一致，即h和w同，c可不同。
#当然实际有3种拼接方式，另两种好像不常见。比如经典网络结构：U-Net


In [2]:
import torch 

In [3]:
t1 = torch.tensor([1,1,1])

In [4]:
t1.unsqueeze(dim=0)

tensor([[1, 1, 1]])

In [5]:
t1.unsqueeze(dim=1)

tensor([[1],
        [1],
        [1]])

In [6]:
print(t1.shape)
print(t1.unsqueeze(dim=0).shape)
print(t1.unsqueeze(dim=1).shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


# Pytorch: Stack  vs  Cat

In [7]:
t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3])

In [10]:
torch.cat((t1,t2,t3),dim=0)   #唯一存在的坐标轴是单个的第一轴          

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [11]:
torch.stack((t1,t2,t3),dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [15]:
torch.cat(
    (
    t1.unsqueeze(0),
    t2.unsqueeze(0),
    t3.unsqueeze(0) 
    )
    ,dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [16]:
torch.cat(                           #对第二个轴进行堆叠
    (
    t1.unsqueeze(1),
    t2.unsqueeze(1),
    t3.unsqueeze(1) 
    )
    ,dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [17]:
###举例

###(1)
#假设有三个单独的图像作为向量，每个图像张量有三个维度，一个通道轴，一个宽度轴，一个高度轴
#现在我们的任务是将这些张量结合在一起形成一个三个图像的单张量（如果我们沿着任何现有的维度把这三个张量连接起来就会把通道宽度高度弄乱，所以使用stack）


###(2)
#假设我们有和之前一样的三个图像，但这一次图像已经有了一个批处理的一个维度，这意味着我们有三个批次，其大小为1
#任务是获得一批三张图像（使用cancat）


#（3）
#假设我们有三个独立的图像张量，只是这次我们已经有了一个批张量
#任务是加入这三个独立的图像
#将三个图像张量的第一个维度进行叠加（stack），即创建了一个长度为3的新批次维度，然后我们可以与已有的批量进行concat